# Autogenerated by LiteX
set -e
source /home/travis/build/timvideos/HDMI2USB-litex-firmware/build/Xilinx/opt/Xilinx/14.7/ISE_DS/settings64.sh

xst -ifn top.xst

ngdbuild  -uc top.ucf top.ngc top.ngd

map -ol high -w -o top_map.ncd top.ngd top.pcf
par -ol high -w top_map.ncd top.ncd top.pcf
bitgen -g Binary:Yes -w -g Compress -g ConfigRate:6 top.ncd top.bit
