# Autogenerated by LiteX / git: 113f7f40
set -e
yosys -q -l top.rpt top.ys
nextpnr-ice40 --lp8k --package cm81 --pcf top.pcf --json top.json --asc top.txt --pre-pack top_pre_pack.py
icepack -s top.txt top.bin
