//--------------------------------------------------------------------------------
// Auto-generated by Migen (0d0e17a) & LiteX (02bfda5e) on 2020-01-30 16:20:50
//--------------------------------------------------------------------------------
module top(
	output reg serial_tx,
	input serial_rx,
	output rgb_led0_r,
	output rgb_led0_g,
	output rgb_led0_b,
	output reg spiflash_cs_n,
	output reg spiflash_clk,
	output reg spiflash_mosi,
	input spiflash_miso
);

wire sb_hfosc;
wire ctrl_reset_reset_re;
wire ctrl_reset_reset_r;
wire ctrl_reset_reset_we;
reg ctrl_reset_reset_w = 1'd0;
reg [31:0] ctrl_storage = 32'd305419896;
reg ctrl_re = 1'd0;
wire [31:0] ctrl_bus_errors_status;
wire ctrl_bus_errors_we;
wire ctrl_reset;
wire ctrl_bus_error;
reg [31:0] ctrl_bus_errors = 32'd0;
wire cpu_reset;
wire [29:0] cpu_ibus_adr;
wire [31:0] cpu_ibus_dat_w;
wire [31:0] cpu_ibus_dat_r;
wire [3:0] cpu_ibus_sel;
wire cpu_ibus_cyc;
wire cpu_ibus_stb;
wire cpu_ibus_ack;
wire cpu_ibus_we;
wire [2:0] cpu_ibus_cti;
wire [1:0] cpu_ibus_bte;
wire cpu_ibus_err;
wire [29:0] cpu_dbus_adr;
wire [31:0] cpu_dbus_dat_w;
wire [31:0] cpu_dbus_dat_r;
wire [3:0] cpu_dbus_sel;
wire cpu_dbus_cyc;
wire cpu_dbus_stb;
wire cpu_dbus_ack;
wire cpu_dbus_we;
wire [2:0] cpu_dbus_cti;
wire [1:0] cpu_dbus_bte;
wire cpu_dbus_err;
reg [31:0] cpu_interrupt = 32'd0;
wire [31:0] cpu_i_adr_o;
wire [31:0] cpu_d_adr_o;
wire [29:0] interface0_soc_bus_adr;
wire [31:0] interface0_soc_bus_dat_w;
wire [31:0] interface0_soc_bus_dat_r;
wire [3:0] interface0_soc_bus_sel;
wire interface0_soc_bus_cyc;
wire interface0_soc_bus_stb;
wire interface0_soc_bus_ack;
wire interface0_soc_bus_we;
wire [2:0] interface0_soc_bus_cti;
wire [1:0] interface0_soc_bus_bte;
wire interface0_soc_bus_err;
wire [29:0] interface1_soc_bus_adr;
wire [31:0] interface1_soc_bus_dat_w;
wire [31:0] interface1_soc_bus_dat_r;
wire [3:0] interface1_soc_bus_sel;
wire interface1_soc_bus_cyc;
wire interface1_soc_bus_stb;
wire interface1_soc_bus_ack;
wire interface1_soc_bus_we;
wire [2:0] interface1_soc_bus_cti;
wire [1:0] interface1_soc_bus_bte;
wire interface1_soc_bus_err;
reg [31:0] uart_phy_storage = 32'd41231686;
reg uart_phy_re = 1'd0;
wire uart_phy_sink_valid;
reg uart_phy_sink_ready = 1'd0;
wire uart_phy_sink_first;
wire uart_phy_sink_last;
wire [7:0] uart_phy_sink_payload_data;
reg uart_phy_uart_clk_txen = 1'd0;
reg [31:0] uart_phy_phase_accumulator_tx = 32'd0;
reg [7:0] uart_phy_tx_reg = 8'd0;
reg [3:0] uart_phy_tx_bitcount = 4'd0;
reg uart_phy_tx_busy = 1'd0;
reg uart_phy_source_valid = 1'd0;
wire uart_phy_source_ready;
reg uart_phy_source_first = 1'd0;
reg uart_phy_source_last = 1'd0;
reg [7:0] uart_phy_source_payload_data = 8'd0;
reg uart_phy_uart_clk_rxen = 1'd0;
reg [31:0] uart_phy_phase_accumulator_rx = 32'd0;
wire uart_phy_rx;
reg uart_phy_rx_r = 1'd0;
reg [7:0] uart_phy_rx_reg = 8'd0;
reg [3:0] uart_phy_rx_bitcount = 4'd0;
reg uart_phy_rx_busy = 1'd0;
wire uart_rxtx_re;
wire [7:0] uart_rxtx_r;
wire uart_rxtx_we;
wire [7:0] uart_rxtx_w;
wire uart_txfull_status;
wire uart_txfull_we;
wire uart_rxempty_status;
wire uart_rxempty_we;
wire uart_irq;
wire uart_tx_status;
reg uart_tx_pending = 1'd0;
wire uart_tx_trigger;
reg uart_tx_clear = 1'd0;
reg uart_tx_old_trigger = 1'd0;
wire uart_rx_status;
reg uart_rx_pending = 1'd0;
wire uart_rx_trigger;
reg uart_rx_clear = 1'd0;
reg uart_rx_old_trigger = 1'd0;
wire uart_eventmanager_status_re;
wire [1:0] uart_eventmanager_status_r;
wire uart_eventmanager_status_we;
reg [1:0] uart_eventmanager_status_w = 2'd0;
wire uart_eventmanager_pending_re;
wire [1:0] uart_eventmanager_pending_r;
wire uart_eventmanager_pending_we;
reg [1:0] uart_eventmanager_pending_w = 2'd0;
reg [1:0] uart_eventmanager_storage = 2'd0;
reg uart_eventmanager_re = 1'd0;
wire uart_tx_fifo_sink_valid;
wire uart_tx_fifo_sink_ready;
reg uart_tx_fifo_sink_first = 1'd0;
reg uart_tx_fifo_sink_last = 1'd0;
wire [7:0] uart_tx_fifo_sink_payload_data;
wire uart_tx_fifo_source_valid;
wire uart_tx_fifo_source_ready;
wire uart_tx_fifo_source_first;
wire uart_tx_fifo_source_last;
wire [7:0] uart_tx_fifo_source_payload_data;
wire uart_tx_fifo_re;
reg uart_tx_fifo_readable = 1'd0;
wire uart_tx_fifo_syncfifo_we;
wire uart_tx_fifo_syncfifo_writable;
wire uart_tx_fifo_syncfifo_re;
wire uart_tx_fifo_syncfifo_readable;
wire [9:0] uart_tx_fifo_syncfifo_din;
wire [9:0] uart_tx_fifo_syncfifo_dout;
reg [4:0] uart_tx_fifo_level0 = 5'd0;
reg uart_tx_fifo_replace = 1'd0;
reg [3:0] uart_tx_fifo_produce = 4'd0;
reg [3:0] uart_tx_fifo_consume = 4'd0;
reg [3:0] uart_tx_fifo_wrport_adr = 4'd0;
wire [9:0] uart_tx_fifo_wrport_dat_r;
wire uart_tx_fifo_wrport_we;
wire [9:0] uart_tx_fifo_wrport_dat_w;
wire uart_tx_fifo_do_read;
wire [3:0] uart_tx_fifo_rdport_adr;
wire [9:0] uart_tx_fifo_rdport_dat_r;
wire uart_tx_fifo_rdport_re;
wire [4:0] uart_tx_fifo_level1;
wire [7:0] uart_tx_fifo_fifo_in_payload_data;
wire uart_tx_fifo_fifo_in_first;
wire uart_tx_fifo_fifo_in_last;
wire [7:0] uart_tx_fifo_fifo_out_payload_data;
wire uart_tx_fifo_fifo_out_first;
wire uart_tx_fifo_fifo_out_last;
wire uart_rx_fifo_sink_valid;
wire uart_rx_fifo_sink_ready;
wire uart_rx_fifo_sink_first;
wire uart_rx_fifo_sink_last;
wire [7:0] uart_rx_fifo_sink_payload_data;
wire uart_rx_fifo_source_valid;
wire uart_rx_fifo_source_ready;
wire uart_rx_fifo_source_first;
wire uart_rx_fifo_source_last;
wire [7:0] uart_rx_fifo_source_payload_data;
wire uart_rx_fifo_re;
reg uart_rx_fifo_readable = 1'd0;
wire uart_rx_fifo_syncfifo_we;
wire uart_rx_fifo_syncfifo_writable;
wire uart_rx_fifo_syncfifo_re;
wire uart_rx_fifo_syncfifo_readable;
wire [9:0] uart_rx_fifo_syncfifo_din;
wire [9:0] uart_rx_fifo_syncfifo_dout;
reg [4:0] uart_rx_fifo_level0 = 5'd0;
reg uart_rx_fifo_replace = 1'd0;
reg [3:0] uart_rx_fifo_produce = 4'd0;
reg [3:0] uart_rx_fifo_consume = 4'd0;
reg [3:0] uart_rx_fifo_wrport_adr = 4'd0;
wire [9:0] uart_rx_fifo_wrport_dat_r;
wire uart_rx_fifo_wrport_we;
wire [9:0] uart_rx_fifo_wrport_dat_w;
wire uart_rx_fifo_do_read;
wire [3:0] uart_rx_fifo_rdport_adr;
wire [9:0] uart_rx_fifo_rdport_dat_r;
wire uart_rx_fifo_rdport_re;
wire [4:0] uart_rx_fifo_level1;
wire [7:0] uart_rx_fifo_fifo_in_payload_data;
wire uart_rx_fifo_fifo_in_first;
wire uart_rx_fifo_fifo_in_last;
wire [7:0] uart_rx_fifo_fifo_out_payload_data;
wire uart_rx_fifo_fifo_out_first;
wire uart_rx_fifo_fifo_out_last;
reg uart_reset = 1'd0;
reg [31:0] timer0_load_storage = 32'd0;
reg timer0_load_re = 1'd0;
reg [31:0] timer0_reload_storage = 32'd0;
reg timer0_reload_re = 1'd0;
reg timer0_en_storage = 1'd0;
reg timer0_en_re = 1'd0;
reg timer0_update_value_storage = 1'd0;
reg timer0_update_value_re = 1'd0;
reg [31:0] timer0_value_status = 32'd0;
wire timer0_value_we;
wire timer0_irq;
wire timer0_zero_status;
reg timer0_zero_pending = 1'd0;
wire timer0_zero_trigger;
reg timer0_zero_clear = 1'd0;
reg timer0_zero_old_trigger = 1'd0;
wire timer0_eventmanager_status_re;
wire timer0_eventmanager_status_r;
wire timer0_eventmanager_status_we;
wire timer0_eventmanager_status_w;
wire timer0_eventmanager_pending_re;
wire timer0_eventmanager_pending_r;
wire timer0_eventmanager_pending_we;
wire timer0_eventmanager_pending_w;
reg timer0_eventmanager_storage = 1'd0;
reg timer0_eventmanager_re = 1'd0;
reg [31:0] timer0_value = 32'd0;
reg [13:0] adr = 14'd0;
reg we = 1'd0;
wire [7:0] dat_w;
wire [7:0] dat_r;
wire [29:0] bus_wishbone_adr;
wire [31:0] bus_wishbone_dat_w;
wire [31:0] bus_wishbone_dat_r;
wire [3:0] bus_wishbone_sel;
wire bus_wishbone_cyc;
wire bus_wishbone_stb;
reg bus_wishbone_ack = 1'd0;
wire bus_wishbone_we;
wire [2:0] bus_wishbone_cti;
wire [1:0] bus_wishbone_bte;
reg bus_wishbone_err = 1'd0;
wire sys_clk;
wire sys_rst;
reg reset = 1'd0;
wire por_clk;
wire por_rst;
reg [11:0] reset_delay = 12'd4095;
wire r_n;
wire g_n;
wire b_n;
wire [2:0] leds;
reg [2:0] leds_storage = 3'd0;
reg leds_re = 1'd0;
wire [29:0] spiflash_bus_adr;
wire [31:0] spiflash_bus_dat_w;
wire [31:0] spiflash_bus_dat_r;
wire [3:0] spiflash_bus_sel;
wire spiflash_bus_cyc;
wire spiflash_bus_stb;
reg spiflash_bus_ack = 1'd0;
wire spiflash_bus_we;
wire [2:0] spiflash_bus_cti;
wire [1:0] spiflash_bus_bte;
reg spiflash_bus_err = 1'd0;
reg [3:0] spiflash_bitbang_storage = 4'd0;
reg spiflash_bitbang_re = 1'd0;
reg spiflash_miso_status = 1'd0;
wire spiflash_miso_we;
reg spiflash_bitbang_en_storage = 1'd0;
reg spiflash_bitbang_en_re = 1'd0;
reg spiflash_cs_n1 = 1'd1;
reg spiflash_clk1 = 1'd0;
reg [31:0] spiflash_sr = 32'd0;
reg spiflash_i = 1'd0;
reg spiflash_miso1 = 1'd0;
reg [7:0] spiflash_counter = 8'd0;
wire [29:0] spram_bus_adr;
wire [31:0] spram_bus_dat_w;
reg [31:0] spram_bus_dat_r = 32'd0;
wire [3:0] spram_bus_sel;
wire spram_bus_cyc;
wire spram_bus_stb;
reg spram_bus_ack = 1'd0;
wire spram_bus_we;
wire [2:0] spram_bus_cti;
wire [1:0] spram_bus_bte;
reg spram_bus_err = 1'd0;
wire [15:0] spram_datain0;
reg [15:0] spram_dataout0 = 16'd0;
wire [3:0] spram_maskwren0;
wire spram_wren0;
reg [15:0] spram_datain00 = 16'd0;
wire [15:0] spram_dataout00;
reg [3:0] spram_maskwren00 = 4'd0;
reg [15:0] spram_datain10 = 16'd0;
wire [15:0] spram_dataout10;
reg [3:0] spram_maskwren10 = 4'd0;
wire [15:0] spram_datain1;
reg [15:0] spram_dataout1 = 16'd0;
wire [3:0] spram_maskwren1;
wire spram_wren1;
reg [15:0] spram_datain01 = 16'd0;
wire [15:0] spram_dataout01;
reg [3:0] spram_maskwren01 = 4'd0;
reg [15:0] spram_datain11 = 16'd0;
wire [15:0] spram_dataout11;
reg [3:0] spram_maskwren11 = 4'd0;
reg state = 1'd0;
reg next_state = 1'd0;
wire [29:0] shared_adr;
wire [31:0] shared_dat_w;
reg [31:0] shared_dat_r = 32'd0;
wire [3:0] shared_sel;
wire shared_cyc;
wire shared_stb;
reg shared_ack = 1'd0;
wire shared_we;
wire [2:0] shared_cti;
wire [1:0] shared_bte;
wire shared_err;
wire [1:0] request;
reg grant = 1'd0;
reg [2:0] slave_sel = 3'd0;
reg [2:0] slave_sel_r = 3'd0;
reg error = 1'd0;
wire wait_1;
wire done;
reg [19:0] count = 20'd1000000;
wire [13:0] csrbankarray_interface0_bank_bus_adr;
wire csrbankarray_interface0_bank_bus_we;
wire [7:0] csrbankarray_interface0_bank_bus_dat_w;
reg [7:0] csrbankarray_interface0_bank_bus_dat_r = 8'd0;
wire csrbankarray_csrbank0_leds_out0_re;
wire [2:0] csrbankarray_csrbank0_leds_out0_r;
wire csrbankarray_csrbank0_leds_out0_we;
wire [2:0] csrbankarray_csrbank0_leds_out0_w;
wire csrbankarray_csrbank0_sel;
wire [13:0] csrbankarray_interface1_bank_bus_adr;
wire csrbankarray_interface1_bank_bus_we;
wire [7:0] csrbankarray_interface1_bank_bus_dat_w;
reg [7:0] csrbankarray_interface1_bank_bus_dat_r = 8'd0;
wire csrbankarray_csrbank1_scratch3_re;
wire [7:0] csrbankarray_csrbank1_scratch3_r;
wire csrbankarray_csrbank1_scratch3_we;
wire [7:0] csrbankarray_csrbank1_scratch3_w;
wire csrbankarray_csrbank1_scratch2_re;
wire [7:0] csrbankarray_csrbank1_scratch2_r;
wire csrbankarray_csrbank1_scratch2_we;
wire [7:0] csrbankarray_csrbank1_scratch2_w;
wire csrbankarray_csrbank1_scratch1_re;
wire [7:0] csrbankarray_csrbank1_scratch1_r;
wire csrbankarray_csrbank1_scratch1_we;
wire [7:0] csrbankarray_csrbank1_scratch1_w;
wire csrbankarray_csrbank1_scratch0_re;
wire [7:0] csrbankarray_csrbank1_scratch0_r;
wire csrbankarray_csrbank1_scratch0_we;
wire [7:0] csrbankarray_csrbank1_scratch0_w;
wire csrbankarray_csrbank1_bus_errors3_re;
wire [7:0] csrbankarray_csrbank1_bus_errors3_r;
wire csrbankarray_csrbank1_bus_errors3_we;
wire [7:0] csrbankarray_csrbank1_bus_errors3_w;
wire csrbankarray_csrbank1_bus_errors2_re;
wire [7:0] csrbankarray_csrbank1_bus_errors2_r;
wire csrbankarray_csrbank1_bus_errors2_we;
wire [7:0] csrbankarray_csrbank1_bus_errors2_w;
wire csrbankarray_csrbank1_bus_errors1_re;
wire [7:0] csrbankarray_csrbank1_bus_errors1_r;
wire csrbankarray_csrbank1_bus_errors1_we;
wire [7:0] csrbankarray_csrbank1_bus_errors1_w;
wire csrbankarray_csrbank1_bus_errors0_re;
wire [7:0] csrbankarray_csrbank1_bus_errors0_r;
wire csrbankarray_csrbank1_bus_errors0_we;
wire [7:0] csrbankarray_csrbank1_bus_errors0_w;
wire csrbankarray_csrbank1_sel;
wire [13:0] csrbankarray_sram_bus_adr;
wire csrbankarray_sram_bus_we;
wire [7:0] csrbankarray_sram_bus_dat_w;
reg [7:0] csrbankarray_sram_bus_dat_r = 8'd0;
wire [2:0] csrbankarray_adr;
wire [7:0] csrbankarray_dat_r;
wire csrbankarray_sel;
reg csrbankarray_sel_r = 1'd0;
wire [13:0] csrbankarray_interface2_bank_bus_adr;
wire csrbankarray_interface2_bank_bus_we;
wire [7:0] csrbankarray_interface2_bank_bus_dat_w;
reg [7:0] csrbankarray_interface2_bank_bus_dat_r = 8'd0;
wire csrbankarray_csrbank2_bitbang0_re;
wire [3:0] csrbankarray_csrbank2_bitbang0_r;
wire csrbankarray_csrbank2_bitbang0_we;
wire [3:0] csrbankarray_csrbank2_bitbang0_w;
wire csrbankarray_csrbank2_miso_re;
wire csrbankarray_csrbank2_miso_r;
wire csrbankarray_csrbank2_miso_we;
wire csrbankarray_csrbank2_miso_w;
wire csrbankarray_csrbank2_bitbang_en0_re;
wire csrbankarray_csrbank2_bitbang_en0_r;
wire csrbankarray_csrbank2_bitbang_en0_we;
wire csrbankarray_csrbank2_bitbang_en0_w;
wire csrbankarray_csrbank2_sel;
wire [13:0] csrbankarray_interface3_bank_bus_adr;
wire csrbankarray_interface3_bank_bus_we;
wire [7:0] csrbankarray_interface3_bank_bus_dat_w;
reg [7:0] csrbankarray_interface3_bank_bus_dat_r = 8'd0;
wire csrbankarray_csrbank3_load3_re;
wire [7:0] csrbankarray_csrbank3_load3_r;
wire csrbankarray_csrbank3_load3_we;
wire [7:0] csrbankarray_csrbank3_load3_w;
wire csrbankarray_csrbank3_load2_re;
wire [7:0] csrbankarray_csrbank3_load2_r;
wire csrbankarray_csrbank3_load2_we;
wire [7:0] csrbankarray_csrbank3_load2_w;
wire csrbankarray_csrbank3_load1_re;
wire [7:0] csrbankarray_csrbank3_load1_r;
wire csrbankarray_csrbank3_load1_we;
wire [7:0] csrbankarray_csrbank3_load1_w;
wire csrbankarray_csrbank3_load0_re;
wire [7:0] csrbankarray_csrbank3_load0_r;
wire csrbankarray_csrbank3_load0_we;
wire [7:0] csrbankarray_csrbank3_load0_w;
wire csrbankarray_csrbank3_reload3_re;
wire [7:0] csrbankarray_csrbank3_reload3_r;
wire csrbankarray_csrbank3_reload3_we;
wire [7:0] csrbankarray_csrbank3_reload3_w;
wire csrbankarray_csrbank3_reload2_re;
wire [7:0] csrbankarray_csrbank3_reload2_r;
wire csrbankarray_csrbank3_reload2_we;
wire [7:0] csrbankarray_csrbank3_reload2_w;
wire csrbankarray_csrbank3_reload1_re;
wire [7:0] csrbankarray_csrbank3_reload1_r;
wire csrbankarray_csrbank3_reload1_we;
wire [7:0] csrbankarray_csrbank3_reload1_w;
wire csrbankarray_csrbank3_reload0_re;
wire [7:0] csrbankarray_csrbank3_reload0_r;
wire csrbankarray_csrbank3_reload0_we;
wire [7:0] csrbankarray_csrbank3_reload0_w;
wire csrbankarray_csrbank3_en0_re;
wire csrbankarray_csrbank3_en0_r;
wire csrbankarray_csrbank3_en0_we;
wire csrbankarray_csrbank3_en0_w;
wire csrbankarray_csrbank3_update_value0_re;
wire csrbankarray_csrbank3_update_value0_r;
wire csrbankarray_csrbank3_update_value0_we;
wire csrbankarray_csrbank3_update_value0_w;
wire csrbankarray_csrbank3_value3_re;
wire [7:0] csrbankarray_csrbank3_value3_r;
wire csrbankarray_csrbank3_value3_we;
wire [7:0] csrbankarray_csrbank3_value3_w;
wire csrbankarray_csrbank3_value2_re;
wire [7:0] csrbankarray_csrbank3_value2_r;
wire csrbankarray_csrbank3_value2_we;
wire [7:0] csrbankarray_csrbank3_value2_w;
wire csrbankarray_csrbank3_value1_re;
wire [7:0] csrbankarray_csrbank3_value1_r;
wire csrbankarray_csrbank3_value1_we;
wire [7:0] csrbankarray_csrbank3_value1_w;
wire csrbankarray_csrbank3_value0_re;
wire [7:0] csrbankarray_csrbank3_value0_r;
wire csrbankarray_csrbank3_value0_we;
wire [7:0] csrbankarray_csrbank3_value0_w;
wire csrbankarray_csrbank3_ev_enable0_re;
wire csrbankarray_csrbank3_ev_enable0_r;
wire csrbankarray_csrbank3_ev_enable0_we;
wire csrbankarray_csrbank3_ev_enable0_w;
wire csrbankarray_csrbank3_sel;
wire [13:0] csrbankarray_interface4_bank_bus_adr;
wire csrbankarray_interface4_bank_bus_we;
wire [7:0] csrbankarray_interface4_bank_bus_dat_w;
reg [7:0] csrbankarray_interface4_bank_bus_dat_r = 8'd0;
wire csrbankarray_csrbank4_txfull_re;
wire csrbankarray_csrbank4_txfull_r;
wire csrbankarray_csrbank4_txfull_we;
wire csrbankarray_csrbank4_txfull_w;
wire csrbankarray_csrbank4_rxempty_re;
wire csrbankarray_csrbank4_rxempty_r;
wire csrbankarray_csrbank4_rxempty_we;
wire csrbankarray_csrbank4_rxempty_w;
wire csrbankarray_csrbank4_ev_enable0_re;
wire [1:0] csrbankarray_csrbank4_ev_enable0_r;
wire csrbankarray_csrbank4_ev_enable0_we;
wire [1:0] csrbankarray_csrbank4_ev_enable0_w;
wire csrbankarray_csrbank4_sel;
wire [13:0] csrbankarray_interface5_bank_bus_adr;
wire csrbankarray_interface5_bank_bus_we;
wire [7:0] csrbankarray_interface5_bank_bus_dat_w;
reg [7:0] csrbankarray_interface5_bank_bus_dat_r = 8'd0;
wire csrbankarray_csrbank5_tuning_word3_re;
wire [7:0] csrbankarray_csrbank5_tuning_word3_r;
wire csrbankarray_csrbank5_tuning_word3_we;
wire [7:0] csrbankarray_csrbank5_tuning_word3_w;
wire csrbankarray_csrbank5_tuning_word2_re;
wire [7:0] csrbankarray_csrbank5_tuning_word2_r;
wire csrbankarray_csrbank5_tuning_word2_we;
wire [7:0] csrbankarray_csrbank5_tuning_word2_w;
wire csrbankarray_csrbank5_tuning_word1_re;
wire [7:0] csrbankarray_csrbank5_tuning_word1_r;
wire csrbankarray_csrbank5_tuning_word1_we;
wire [7:0] csrbankarray_csrbank5_tuning_word1_w;
wire csrbankarray_csrbank5_tuning_word0_re;
wire [7:0] csrbankarray_csrbank5_tuning_word0_r;
wire csrbankarray_csrbank5_tuning_word0_we;
wire [7:0] csrbankarray_csrbank5_tuning_word0_w;
wire csrbankarray_csrbank5_sel;
wire [13:0] csrcon_adr;
wire csrcon_we;
wire [7:0] csrcon_dat_w;
wire [7:0] csrcon_dat_r;
reg [29:0] array_muxed0 = 30'd0;
reg [31:0] array_muxed1 = 32'd0;
reg [3:0] array_muxed2 = 4'd0;
reg array_muxed3 = 1'd0;
reg array_muxed4 = 1'd0;
reg array_muxed5 = 1'd0;
reg [2:0] array_muxed6 = 3'd0;
reg [1:0] array_muxed7 = 2'd0;
reg regs0 = 1'd0;
reg regs1 = 1'd0;
wire rst1;

assign cpu_reset = ctrl_reset;
assign ctrl_bus_error = error;
always @(*) begin
	cpu_interrupt <= 32'd0;
	cpu_interrupt[1] <= timer0_irq;
	cpu_interrupt[0] <= uart_irq;
end
assign ctrl_reset = ctrl_reset_reset_re;
assign ctrl_bus_errors_status = ctrl_bus_errors;
assign cpu_ibus_adr = cpu_i_adr_o[31:2];
assign cpu_dbus_adr = cpu_d_adr_o[31:2];
assign interface0_soc_bus_adr = cpu_ibus_adr;
assign interface0_soc_bus_dat_w = cpu_ibus_dat_w;
assign cpu_ibus_dat_r = interface0_soc_bus_dat_r;
assign interface0_soc_bus_sel = cpu_ibus_sel;
assign interface0_soc_bus_cyc = cpu_ibus_cyc;
assign interface0_soc_bus_stb = cpu_ibus_stb;
assign cpu_ibus_ack = interface0_soc_bus_ack;
assign interface0_soc_bus_we = cpu_ibus_we;
assign interface0_soc_bus_cti = cpu_ibus_cti;
assign interface0_soc_bus_bte = cpu_ibus_bte;
assign cpu_ibus_err = interface0_soc_bus_err;
assign interface1_soc_bus_adr = cpu_dbus_adr;
assign interface1_soc_bus_dat_w = cpu_dbus_dat_w;
assign cpu_dbus_dat_r = interface1_soc_bus_dat_r;
assign interface1_soc_bus_sel = cpu_dbus_sel;
assign interface1_soc_bus_cyc = cpu_dbus_cyc;
assign interface1_soc_bus_stb = cpu_dbus_stb;
assign cpu_dbus_ack = interface1_soc_bus_ack;
assign interface1_soc_bus_we = cpu_dbus_we;
assign interface1_soc_bus_cti = cpu_dbus_cti;
assign interface1_soc_bus_bte = cpu_dbus_bte;
assign cpu_dbus_err = interface1_soc_bus_err;
assign uart_tx_fifo_sink_valid = uart_rxtx_re;
assign uart_tx_fifo_sink_payload_data = uart_rxtx_r;
assign uart_txfull_status = (~uart_tx_fifo_sink_ready);
assign uart_phy_sink_valid = uart_tx_fifo_source_valid;
assign uart_tx_fifo_source_ready = uart_phy_sink_ready;
assign uart_phy_sink_first = uart_tx_fifo_source_first;
assign uart_phy_sink_last = uart_tx_fifo_source_last;
assign uart_phy_sink_payload_data = uart_tx_fifo_source_payload_data;
assign uart_tx_trigger = (~uart_tx_fifo_sink_ready);
assign uart_rx_fifo_sink_valid = uart_phy_source_valid;
assign uart_phy_source_ready = uart_rx_fifo_sink_ready;
assign uart_rx_fifo_sink_first = uart_phy_source_first;
assign uart_rx_fifo_sink_last = uart_phy_source_last;
assign uart_rx_fifo_sink_payload_data = uart_phy_source_payload_data;
assign uart_rxempty_status = (~uart_rx_fifo_source_valid);
assign uart_rxtx_w = uart_rx_fifo_source_payload_data;
assign uart_rx_fifo_source_ready = uart_rx_clear;
assign uart_rx_trigger = (~uart_rx_fifo_source_valid);
always @(*) begin
	uart_tx_clear <= 1'd0;
	if ((uart_eventmanager_pending_re & uart_eventmanager_pending_r[0])) begin
		uart_tx_clear <= 1'd1;
	end
end
always @(*) begin
	uart_eventmanager_status_w <= 2'd0;
	uart_eventmanager_status_w[0] <= uart_tx_status;
	uart_eventmanager_status_w[1] <= uart_rx_status;
end
always @(*) begin
	uart_rx_clear <= 1'd0;
	if ((uart_eventmanager_pending_re & uart_eventmanager_pending_r[1])) begin
		uart_rx_clear <= 1'd1;
	end
end
always @(*) begin
	uart_eventmanager_pending_w <= 2'd0;
	uart_eventmanager_pending_w[0] <= uart_tx_pending;
	uart_eventmanager_pending_w[1] <= uart_rx_pending;
end
assign uart_irq = ((uart_eventmanager_pending_w[0] & uart_eventmanager_storage[0]) | (uart_eventmanager_pending_w[1] & uart_eventmanager_storage[1]));
assign uart_tx_status = uart_tx_trigger;
assign uart_rx_status = uart_rx_trigger;
assign uart_tx_fifo_syncfifo_din = {uart_tx_fifo_fifo_in_last, uart_tx_fifo_fifo_in_first, uart_tx_fifo_fifo_in_payload_data};
assign {uart_tx_fifo_fifo_out_last, uart_tx_fifo_fifo_out_first, uart_tx_fifo_fifo_out_payload_data} = uart_tx_fifo_syncfifo_dout;
assign uart_tx_fifo_sink_ready = uart_tx_fifo_syncfifo_writable;
assign uart_tx_fifo_syncfifo_we = uart_tx_fifo_sink_valid;
assign uart_tx_fifo_fifo_in_first = uart_tx_fifo_sink_first;
assign uart_tx_fifo_fifo_in_last = uart_tx_fifo_sink_last;
assign uart_tx_fifo_fifo_in_payload_data = uart_tx_fifo_sink_payload_data;
assign uart_tx_fifo_source_valid = uart_tx_fifo_readable;
assign uart_tx_fifo_source_first = uart_tx_fifo_fifo_out_first;
assign uart_tx_fifo_source_last = uart_tx_fifo_fifo_out_last;
assign uart_tx_fifo_source_payload_data = uart_tx_fifo_fifo_out_payload_data;
assign uart_tx_fifo_re = uart_tx_fifo_source_ready;
assign uart_tx_fifo_syncfifo_re = (uart_tx_fifo_syncfifo_readable & ((~uart_tx_fifo_readable) | uart_tx_fifo_re));
assign uart_tx_fifo_level1 = (uart_tx_fifo_level0 + uart_tx_fifo_readable);
always @(*) begin
	uart_tx_fifo_wrport_adr <= 4'd0;
	if (uart_tx_fifo_replace) begin
		uart_tx_fifo_wrport_adr <= (uart_tx_fifo_produce - 1'd1);
	end else begin
		uart_tx_fifo_wrport_adr <= uart_tx_fifo_produce;
	end
end
assign uart_tx_fifo_wrport_dat_w = uart_tx_fifo_syncfifo_din;
assign uart_tx_fifo_wrport_we = (uart_tx_fifo_syncfifo_we & (uart_tx_fifo_syncfifo_writable | uart_tx_fifo_replace));
assign uart_tx_fifo_do_read = (uart_tx_fifo_syncfifo_readable & uart_tx_fifo_syncfifo_re);
assign uart_tx_fifo_rdport_adr = uart_tx_fifo_consume;
assign uart_tx_fifo_syncfifo_dout = uart_tx_fifo_rdport_dat_r;
assign uart_tx_fifo_rdport_re = uart_tx_fifo_do_read;
assign uart_tx_fifo_syncfifo_writable = (uart_tx_fifo_level0 != 5'd16);
assign uart_tx_fifo_syncfifo_readable = (uart_tx_fifo_level0 != 1'd0);
assign uart_rx_fifo_syncfifo_din = {uart_rx_fifo_fifo_in_last, uart_rx_fifo_fifo_in_first, uart_rx_fifo_fifo_in_payload_data};
assign {uart_rx_fifo_fifo_out_last, uart_rx_fifo_fifo_out_first, uart_rx_fifo_fifo_out_payload_data} = uart_rx_fifo_syncfifo_dout;
assign uart_rx_fifo_sink_ready = uart_rx_fifo_syncfifo_writable;
assign uart_rx_fifo_syncfifo_we = uart_rx_fifo_sink_valid;
assign uart_rx_fifo_fifo_in_first = uart_rx_fifo_sink_first;
assign uart_rx_fifo_fifo_in_last = uart_rx_fifo_sink_last;
assign uart_rx_fifo_fifo_in_payload_data = uart_rx_fifo_sink_payload_data;
assign uart_rx_fifo_source_valid = uart_rx_fifo_readable;
assign uart_rx_fifo_source_first = uart_rx_fifo_fifo_out_first;
assign uart_rx_fifo_source_last = uart_rx_fifo_fifo_out_last;
assign uart_rx_fifo_source_payload_data = uart_rx_fifo_fifo_out_payload_data;
assign uart_rx_fifo_re = uart_rx_fifo_source_ready;
assign uart_rx_fifo_syncfifo_re = (uart_rx_fifo_syncfifo_readable & ((~uart_rx_fifo_readable) | uart_rx_fifo_re));
assign uart_rx_fifo_level1 = (uart_rx_fifo_level0 + uart_rx_fifo_readable);
always @(*) begin
	uart_rx_fifo_wrport_adr <= 4'd0;
	if (uart_rx_fifo_replace) begin
		uart_rx_fifo_wrport_adr <= (uart_rx_fifo_produce - 1'd1);
	end else begin
		uart_rx_fifo_wrport_adr <= uart_rx_fifo_produce;
	end
end
assign uart_rx_fifo_wrport_dat_w = uart_rx_fifo_syncfifo_din;
assign uart_rx_fifo_wrport_we = (uart_rx_fifo_syncfifo_we & (uart_rx_fifo_syncfifo_writable | uart_rx_fifo_replace));
assign uart_rx_fifo_do_read = (uart_rx_fifo_syncfifo_readable & uart_rx_fifo_syncfifo_re);
assign uart_rx_fifo_rdport_adr = uart_rx_fifo_consume;
assign uart_rx_fifo_syncfifo_dout = uart_rx_fifo_rdport_dat_r;
assign uart_rx_fifo_rdport_re = uart_rx_fifo_do_read;
assign uart_rx_fifo_syncfifo_writable = (uart_rx_fifo_level0 != 5'd16);
assign uart_rx_fifo_syncfifo_readable = (uart_rx_fifo_level0 != 1'd0);
assign timer0_zero_trigger = (timer0_value != 1'd0);
assign timer0_eventmanager_status_w = timer0_zero_status;
always @(*) begin
	timer0_zero_clear <= 1'd0;
	if ((timer0_eventmanager_pending_re & timer0_eventmanager_pending_r)) begin
		timer0_zero_clear <= 1'd1;
	end
end
assign timer0_eventmanager_pending_w = timer0_zero_pending;
assign timer0_irq = (timer0_eventmanager_pending_w & timer0_eventmanager_storage);
assign timer0_zero_status = timer0_zero_trigger;
assign dat_w = bus_wishbone_dat_w;
assign bus_wishbone_dat_r = dat_r;
always @(*) begin
	we <= 1'd0;
	bus_wishbone_ack <= 1'd0;
	next_state <= 1'd0;
	adr <= 14'd0;
	next_state <= state;
	case (state)
		1'd1: begin
			bus_wishbone_ack <= 1'd1;
			next_state <= 1'd0;
		end
		default: begin
			if ((bus_wishbone_cyc & bus_wishbone_stb)) begin
				adr <= bus_wishbone_adr;
				we <= bus_wishbone_we;
				next_state <= 1'd1;
			end
		end
	endcase
end
assign sys_clk = sb_hfosc;
assign por_clk = sys_clk;
assign sys_rst = (reset_delay != 1'd0);
assign rgb_led0_r = (~r_n);
assign rgb_led0_g = (~g_n);
assign rgb_led0_b = (~b_n);
assign r_n = leds[0];
assign g_n = leds[1];
assign b_n = leds[2];
assign leds = leds_storage;
assign spiflash_bus_dat_r = spiflash_sr;
always @(*) begin
	spiflash_mosi <= 1'd0;
	spiflash_cs_n <= 1'd0;
	spiflash_clk <= 1'd0;
	spiflash_miso_status <= 1'd0;
	if (spiflash_bitbang_en_storage) begin
		spiflash_clk <= spiflash_bitbang_storage[1];
		spiflash_cs_n <= spiflash_bitbang_storage[2];
		if (spiflash_bitbang_storage[1]) begin
			spiflash_miso_status <= spiflash_miso;
		end
		spiflash_mosi <= spiflash_bitbang_storage[0];
	end else begin
		spiflash_clk <= spiflash_clk1;
		spiflash_cs_n <= spiflash_cs_n1;
		spiflash_mosi <= spiflash_sr[31];
	end
end
assign spram_datain0 = spram_bus_dat_w[15:0];
assign spram_maskwren0 = {{2{spram_bus_sel[1]}}, {2{spram_bus_sel[0]}}};
assign spram_wren0 = ((spram_bus_we & spram_bus_stb) & spram_bus_cyc);
always @(*) begin
	spram_maskwren00 <= 4'd0;
	spram_datain10 <= 16'd0;
	spram_dataout0 <= 16'd0;
	spram_datain00 <= 16'd0;
	spram_maskwren10 <= 4'd0;
	if (spram_bus_adr[14]) begin
		spram_datain10 <= spram_datain0;
		spram_dataout0 <= spram_dataout10;
		spram_maskwren10 <= spram_maskwren0;
	end else begin
		spram_datain00 <= spram_datain0;
		spram_dataout0 <= spram_dataout00;
		spram_maskwren00 <= spram_maskwren0;
	end
end
always @(*) begin
	spram_bus_dat_r <= 32'd0;
	spram_bus_dat_r[0] <= spram_dataout0[0];
	spram_bus_dat_r[1] <= spram_dataout0[1];
	spram_bus_dat_r[2] <= spram_dataout0[2];
	spram_bus_dat_r[3] <= spram_dataout0[3];
	spram_bus_dat_r[4] <= spram_dataout0[4];
	spram_bus_dat_r[5] <= spram_dataout0[5];
	spram_bus_dat_r[6] <= spram_dataout0[6];
	spram_bus_dat_r[7] <= spram_dataout0[7];
	spram_bus_dat_r[8] <= spram_dataout0[8];
	spram_bus_dat_r[9] <= spram_dataout0[9];
	spram_bus_dat_r[10] <= spram_dataout0[10];
	spram_bus_dat_r[11] <= spram_dataout0[11];
	spram_bus_dat_r[12] <= spram_dataout0[12];
	spram_bus_dat_r[13] <= spram_dataout0[13];
	spram_bus_dat_r[14] <= spram_dataout0[14];
	spram_bus_dat_r[15] <= spram_dataout0[15];
	spram_bus_dat_r[16] <= spram_dataout1[0];
	spram_bus_dat_r[17] <= spram_dataout1[1];
	spram_bus_dat_r[18] <= spram_dataout1[2];
	spram_bus_dat_r[19] <= spram_dataout1[3];
	spram_bus_dat_r[20] <= spram_dataout1[4];
	spram_bus_dat_r[21] <= spram_dataout1[5];
	spram_bus_dat_r[22] <= spram_dataout1[6];
	spram_bus_dat_r[23] <= spram_dataout1[7];
	spram_bus_dat_r[24] <= spram_dataout1[8];
	spram_bus_dat_r[25] <= spram_dataout1[9];
	spram_bus_dat_r[26] <= spram_dataout1[10];
	spram_bus_dat_r[27] <= spram_dataout1[11];
	spram_bus_dat_r[28] <= spram_dataout1[12];
	spram_bus_dat_r[29] <= spram_dataout1[13];
	spram_bus_dat_r[30] <= spram_dataout1[14];
	spram_bus_dat_r[31] <= spram_dataout1[15];
end
assign spram_datain1 = spram_bus_dat_w[31:16];
assign spram_maskwren1 = {{2{spram_bus_sel[3]}}, {2{spram_bus_sel[2]}}};
assign spram_wren1 = ((spram_bus_we & spram_bus_stb) & spram_bus_cyc);
always @(*) begin
	spram_maskwren11 <= 4'd0;
	spram_dataout1 <= 16'd0;
	spram_datain01 <= 16'd0;
	spram_maskwren01 <= 4'd0;
	spram_datain11 <= 16'd0;
	if (spram_bus_adr[14]) begin
		spram_datain11 <= spram_datain1;
		spram_dataout1 <= spram_dataout11;
		spram_maskwren11 <= spram_maskwren1;
	end else begin
		spram_datain01 <= spram_datain1;
		spram_dataout1 <= spram_dataout01;
		spram_maskwren01 <= spram_maskwren1;
	end
end
assign shared_adr = array_muxed0;
assign shared_dat_w = array_muxed1;
assign shared_sel = array_muxed2;
assign shared_cyc = array_muxed3;
assign shared_stb = array_muxed4;
assign shared_we = array_muxed5;
assign shared_cti = array_muxed6;
assign shared_bte = array_muxed7;
assign interface0_soc_bus_dat_r = shared_dat_r;
assign interface1_soc_bus_dat_r = shared_dat_r;
assign interface0_soc_bus_ack = (shared_ack & (grant == 1'd0));
assign interface1_soc_bus_ack = (shared_ack & (grant == 1'd1));
assign interface0_soc_bus_err = (shared_err & (grant == 1'd0));
assign interface1_soc_bus_err = (shared_err & (grant == 1'd1));
assign request = {interface1_soc_bus_cyc, interface0_soc_bus_cyc};
always @(*) begin
	slave_sel <= 3'd0;
	slave_sel[0] <= (shared_adr[28:22] == 2'd2);
	slave_sel[1] <= (shared_adr[28:20] == 8'd128);
	slave_sel[2] <= (shared_adr[28:15] == 8'd128);
end
assign bus_wishbone_adr = shared_adr;
assign bus_wishbone_dat_w = shared_dat_w;
assign bus_wishbone_sel = shared_sel;
assign bus_wishbone_stb = shared_stb;
assign bus_wishbone_we = shared_we;
assign bus_wishbone_cti = shared_cti;
assign bus_wishbone_bte = shared_bte;
assign spiflash_bus_adr = shared_adr;
assign spiflash_bus_dat_w = shared_dat_w;
assign spiflash_bus_sel = shared_sel;
assign spiflash_bus_stb = shared_stb;
assign spiflash_bus_we = shared_we;
assign spiflash_bus_cti = shared_cti;
assign spiflash_bus_bte = shared_bte;
assign spram_bus_adr = shared_adr;
assign spram_bus_dat_w = shared_dat_w;
assign spram_bus_sel = shared_sel;
assign spram_bus_stb = shared_stb;
assign spram_bus_we = shared_we;
assign spram_bus_cti = shared_cti;
assign spram_bus_bte = shared_bte;
assign bus_wishbone_cyc = (shared_cyc & slave_sel[0]);
assign spiflash_bus_cyc = (shared_cyc & slave_sel[1]);
assign spram_bus_cyc = (shared_cyc & slave_sel[2]);
assign shared_err = ((bus_wishbone_err | spiflash_bus_err) | spram_bus_err);
assign wait_1 = ((shared_stb & shared_cyc) & (~shared_ack));
always @(*) begin
	shared_ack <= 1'd0;
	shared_dat_r <= 32'd0;
	error <= 1'd0;
	shared_ack <= ((bus_wishbone_ack | spiflash_bus_ack) | spram_bus_ack);
	shared_dat_r <= ((({32{slave_sel_r[0]}} & bus_wishbone_dat_r) | ({32{slave_sel_r[1]}} & spiflash_bus_dat_r)) | ({32{slave_sel_r[2]}} & spram_bus_dat_r));
	if (done) begin
		shared_dat_r <= 32'd4294967295;
		shared_ack <= 1'd1;
		error <= 1'd1;
	end
end
assign done = (count == 1'd0);
assign csrbankarray_csrbank0_sel = (csrbankarray_interface0_bank_bus_adr[13:9] == 1'd1);
assign csrbankarray_csrbank0_leds_out0_r = csrbankarray_interface0_bank_bus_dat_w[2:0];
assign csrbankarray_csrbank0_leds_out0_re = ((csrbankarray_csrbank0_sel & csrbankarray_interface0_bank_bus_we) & (csrbankarray_interface0_bank_bus_adr[0] == 1'd0));
assign csrbankarray_csrbank0_leds_out0_we = ((csrbankarray_csrbank0_sel & (~csrbankarray_interface0_bank_bus_we)) & (csrbankarray_interface0_bank_bus_adr[0] == 1'd0));
assign csrbankarray_csrbank0_leds_out0_w = leds_storage[2:0];
assign csrbankarray_csrbank1_sel = (csrbankarray_interface1_bank_bus_adr[13:9] == 2'd2);
assign ctrl_reset_reset_r = csrbankarray_interface1_bank_bus_dat_w[0];
assign ctrl_reset_reset_re = ((csrbankarray_csrbank1_sel & csrbankarray_interface1_bank_bus_we) & (csrbankarray_interface1_bank_bus_adr[3:0] == 1'd0));
assign ctrl_reset_reset_we = ((csrbankarray_csrbank1_sel & (~csrbankarray_interface1_bank_bus_we)) & (csrbankarray_interface1_bank_bus_adr[3:0] == 1'd0));
assign csrbankarray_csrbank1_scratch3_r = csrbankarray_interface1_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank1_scratch3_re = ((csrbankarray_csrbank1_sel & csrbankarray_interface1_bank_bus_we) & (csrbankarray_interface1_bank_bus_adr[3:0] == 1'd1));
assign csrbankarray_csrbank1_scratch3_we = ((csrbankarray_csrbank1_sel & (~csrbankarray_interface1_bank_bus_we)) & (csrbankarray_interface1_bank_bus_adr[3:0] == 1'd1));
assign csrbankarray_csrbank1_scratch2_r = csrbankarray_interface1_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank1_scratch2_re = ((csrbankarray_csrbank1_sel & csrbankarray_interface1_bank_bus_we) & (csrbankarray_interface1_bank_bus_adr[3:0] == 2'd2));
assign csrbankarray_csrbank1_scratch2_we = ((csrbankarray_csrbank1_sel & (~csrbankarray_interface1_bank_bus_we)) & (csrbankarray_interface1_bank_bus_adr[3:0] == 2'd2));
assign csrbankarray_csrbank1_scratch1_r = csrbankarray_interface1_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank1_scratch1_re = ((csrbankarray_csrbank1_sel & csrbankarray_interface1_bank_bus_we) & (csrbankarray_interface1_bank_bus_adr[3:0] == 2'd3));
assign csrbankarray_csrbank1_scratch1_we = ((csrbankarray_csrbank1_sel & (~csrbankarray_interface1_bank_bus_we)) & (csrbankarray_interface1_bank_bus_adr[3:0] == 2'd3));
assign csrbankarray_csrbank1_scratch0_r = csrbankarray_interface1_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank1_scratch0_re = ((csrbankarray_csrbank1_sel & csrbankarray_interface1_bank_bus_we) & (csrbankarray_interface1_bank_bus_adr[3:0] == 3'd4));
assign csrbankarray_csrbank1_scratch0_we = ((csrbankarray_csrbank1_sel & (~csrbankarray_interface1_bank_bus_we)) & (csrbankarray_interface1_bank_bus_adr[3:0] == 3'd4));
assign csrbankarray_csrbank1_bus_errors3_r = csrbankarray_interface1_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank1_bus_errors3_re = ((csrbankarray_csrbank1_sel & csrbankarray_interface1_bank_bus_we) & (csrbankarray_interface1_bank_bus_adr[3:0] == 3'd5));
assign csrbankarray_csrbank1_bus_errors3_we = ((csrbankarray_csrbank1_sel & (~csrbankarray_interface1_bank_bus_we)) & (csrbankarray_interface1_bank_bus_adr[3:0] == 3'd5));
assign csrbankarray_csrbank1_bus_errors2_r = csrbankarray_interface1_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank1_bus_errors2_re = ((csrbankarray_csrbank1_sel & csrbankarray_interface1_bank_bus_we) & (csrbankarray_interface1_bank_bus_adr[3:0] == 3'd6));
assign csrbankarray_csrbank1_bus_errors2_we = ((csrbankarray_csrbank1_sel & (~csrbankarray_interface1_bank_bus_we)) & (csrbankarray_interface1_bank_bus_adr[3:0] == 3'd6));
assign csrbankarray_csrbank1_bus_errors1_r = csrbankarray_interface1_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank1_bus_errors1_re = ((csrbankarray_csrbank1_sel & csrbankarray_interface1_bank_bus_we) & (csrbankarray_interface1_bank_bus_adr[3:0] == 3'd7));
assign csrbankarray_csrbank1_bus_errors1_we = ((csrbankarray_csrbank1_sel & (~csrbankarray_interface1_bank_bus_we)) & (csrbankarray_interface1_bank_bus_adr[3:0] == 3'd7));
assign csrbankarray_csrbank1_bus_errors0_r = csrbankarray_interface1_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank1_bus_errors0_re = ((csrbankarray_csrbank1_sel & csrbankarray_interface1_bank_bus_we) & (csrbankarray_interface1_bank_bus_adr[3:0] == 4'd8));
assign csrbankarray_csrbank1_bus_errors0_we = ((csrbankarray_csrbank1_sel & (~csrbankarray_interface1_bank_bus_we)) & (csrbankarray_interface1_bank_bus_adr[3:0] == 4'd8));
assign csrbankarray_csrbank1_scratch3_w = ctrl_storage[31:24];
assign csrbankarray_csrbank1_scratch2_w = ctrl_storage[23:16];
assign csrbankarray_csrbank1_scratch1_w = ctrl_storage[15:8];
assign csrbankarray_csrbank1_scratch0_w = ctrl_storage[7:0];
assign csrbankarray_csrbank1_bus_errors3_w = ctrl_bus_errors_status[31:24];
assign csrbankarray_csrbank1_bus_errors2_w = ctrl_bus_errors_status[23:16];
assign csrbankarray_csrbank1_bus_errors1_w = ctrl_bus_errors_status[15:8];
assign csrbankarray_csrbank1_bus_errors0_w = ctrl_bus_errors_status[7:0];
assign ctrl_bus_errors_we = csrbankarray_csrbank1_bus_errors0_we;
assign csrbankarray_sel = (csrbankarray_sram_bus_adr[13:9] == 3'd6);
always @(*) begin
	csrbankarray_sram_bus_dat_r <= 8'd0;
	if (csrbankarray_sel_r) begin
		csrbankarray_sram_bus_dat_r <= csrbankarray_dat_r;
	end
end
assign csrbankarray_adr = csrbankarray_sram_bus_adr[2:0];
assign csrbankarray_csrbank2_sel = (csrbankarray_interface2_bank_bus_adr[13:9] == 1'd0);
assign csrbankarray_csrbank2_bitbang0_r = csrbankarray_interface2_bank_bus_dat_w[3:0];
assign csrbankarray_csrbank2_bitbang0_re = ((csrbankarray_csrbank2_sel & csrbankarray_interface2_bank_bus_we) & (csrbankarray_interface2_bank_bus_adr[1:0] == 1'd0));
assign csrbankarray_csrbank2_bitbang0_we = ((csrbankarray_csrbank2_sel & (~csrbankarray_interface2_bank_bus_we)) & (csrbankarray_interface2_bank_bus_adr[1:0] == 1'd0));
assign csrbankarray_csrbank2_miso_r = csrbankarray_interface2_bank_bus_dat_w[0];
assign csrbankarray_csrbank2_miso_re = ((csrbankarray_csrbank2_sel & csrbankarray_interface2_bank_bus_we) & (csrbankarray_interface2_bank_bus_adr[1:0] == 1'd1));
assign csrbankarray_csrbank2_miso_we = ((csrbankarray_csrbank2_sel & (~csrbankarray_interface2_bank_bus_we)) & (csrbankarray_interface2_bank_bus_adr[1:0] == 1'd1));
assign csrbankarray_csrbank2_bitbang_en0_r = csrbankarray_interface2_bank_bus_dat_w[0];
assign csrbankarray_csrbank2_bitbang_en0_re = ((csrbankarray_csrbank2_sel & csrbankarray_interface2_bank_bus_we) & (csrbankarray_interface2_bank_bus_adr[1:0] == 2'd2));
assign csrbankarray_csrbank2_bitbang_en0_we = ((csrbankarray_csrbank2_sel & (~csrbankarray_interface2_bank_bus_we)) & (csrbankarray_interface2_bank_bus_adr[1:0] == 2'd2));
assign csrbankarray_csrbank2_bitbang0_w = spiflash_bitbang_storage[3:0];
assign csrbankarray_csrbank2_miso_w = spiflash_miso_status;
assign spiflash_miso_we = csrbankarray_csrbank2_miso_we;
assign csrbankarray_csrbank2_bitbang_en0_w = spiflash_bitbang_en_storage;
assign csrbankarray_csrbank3_sel = (csrbankarray_interface3_bank_bus_adr[13:9] == 3'd7);
assign csrbankarray_csrbank3_load3_r = csrbankarray_interface3_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank3_load3_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 1'd0));
assign csrbankarray_csrbank3_load3_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 1'd0));
assign csrbankarray_csrbank3_load2_r = csrbankarray_interface3_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank3_load2_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 1'd1));
assign csrbankarray_csrbank3_load2_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 1'd1));
assign csrbankarray_csrbank3_load1_r = csrbankarray_interface3_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank3_load1_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 2'd2));
assign csrbankarray_csrbank3_load1_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 2'd2));
assign csrbankarray_csrbank3_load0_r = csrbankarray_interface3_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank3_load0_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 2'd3));
assign csrbankarray_csrbank3_load0_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 2'd3));
assign csrbankarray_csrbank3_reload3_r = csrbankarray_interface3_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank3_reload3_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 3'd4));
assign csrbankarray_csrbank3_reload3_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 3'd4));
assign csrbankarray_csrbank3_reload2_r = csrbankarray_interface3_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank3_reload2_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 3'd5));
assign csrbankarray_csrbank3_reload2_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 3'd5));
assign csrbankarray_csrbank3_reload1_r = csrbankarray_interface3_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank3_reload1_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 3'd6));
assign csrbankarray_csrbank3_reload1_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 3'd6));
assign csrbankarray_csrbank3_reload0_r = csrbankarray_interface3_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank3_reload0_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 3'd7));
assign csrbankarray_csrbank3_reload0_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 3'd7));
assign csrbankarray_csrbank3_en0_r = csrbankarray_interface3_bank_bus_dat_w[0];
assign csrbankarray_csrbank3_en0_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd8));
assign csrbankarray_csrbank3_en0_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd8));
assign csrbankarray_csrbank3_update_value0_r = csrbankarray_interface3_bank_bus_dat_w[0];
assign csrbankarray_csrbank3_update_value0_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd9));
assign csrbankarray_csrbank3_update_value0_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd9));
assign csrbankarray_csrbank3_value3_r = csrbankarray_interface3_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank3_value3_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd10));
assign csrbankarray_csrbank3_value3_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd10));
assign csrbankarray_csrbank3_value2_r = csrbankarray_interface3_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank3_value2_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd11));
assign csrbankarray_csrbank3_value2_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd11));
assign csrbankarray_csrbank3_value1_r = csrbankarray_interface3_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank3_value1_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd12));
assign csrbankarray_csrbank3_value1_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd12));
assign csrbankarray_csrbank3_value0_r = csrbankarray_interface3_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank3_value0_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd13));
assign csrbankarray_csrbank3_value0_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd13));
assign timer0_eventmanager_status_r = csrbankarray_interface3_bank_bus_dat_w[0];
assign timer0_eventmanager_status_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd14));
assign timer0_eventmanager_status_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd14));
assign timer0_eventmanager_pending_r = csrbankarray_interface3_bank_bus_dat_w[0];
assign timer0_eventmanager_pending_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd15));
assign timer0_eventmanager_pending_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 4'd15));
assign csrbankarray_csrbank3_ev_enable0_r = csrbankarray_interface3_bank_bus_dat_w[0];
assign csrbankarray_csrbank3_ev_enable0_re = ((csrbankarray_csrbank3_sel & csrbankarray_interface3_bank_bus_we) & (csrbankarray_interface3_bank_bus_adr[4:0] == 5'd16));
assign csrbankarray_csrbank3_ev_enable0_we = ((csrbankarray_csrbank3_sel & (~csrbankarray_interface3_bank_bus_we)) & (csrbankarray_interface3_bank_bus_adr[4:0] == 5'd16));
assign csrbankarray_csrbank3_load3_w = timer0_load_storage[31:24];
assign csrbankarray_csrbank3_load2_w = timer0_load_storage[23:16];
assign csrbankarray_csrbank3_load1_w = timer0_load_storage[15:8];
assign csrbankarray_csrbank3_load0_w = timer0_load_storage[7:0];
assign csrbankarray_csrbank3_reload3_w = timer0_reload_storage[31:24];
assign csrbankarray_csrbank3_reload2_w = timer0_reload_storage[23:16];
assign csrbankarray_csrbank3_reload1_w = timer0_reload_storage[15:8];
assign csrbankarray_csrbank3_reload0_w = timer0_reload_storage[7:0];
assign csrbankarray_csrbank3_en0_w = timer0_en_storage;
assign csrbankarray_csrbank3_update_value0_w = timer0_update_value_storage;
assign csrbankarray_csrbank3_value3_w = timer0_value_status[31:24];
assign csrbankarray_csrbank3_value2_w = timer0_value_status[23:16];
assign csrbankarray_csrbank3_value1_w = timer0_value_status[15:8];
assign csrbankarray_csrbank3_value0_w = timer0_value_status[7:0];
assign timer0_value_we = csrbankarray_csrbank3_value0_we;
assign csrbankarray_csrbank3_ev_enable0_w = timer0_eventmanager_storage;
assign csrbankarray_csrbank4_sel = (csrbankarray_interface4_bank_bus_adr[13:9] == 3'd5);
assign uart_rxtx_r = csrbankarray_interface4_bank_bus_dat_w[7:0];
assign uart_rxtx_re = ((csrbankarray_csrbank4_sel & csrbankarray_interface4_bank_bus_we) & (csrbankarray_interface4_bank_bus_adr[2:0] == 1'd0));
assign uart_rxtx_we = ((csrbankarray_csrbank4_sel & (~csrbankarray_interface4_bank_bus_we)) & (csrbankarray_interface4_bank_bus_adr[2:0] == 1'd0));
assign csrbankarray_csrbank4_txfull_r = csrbankarray_interface4_bank_bus_dat_w[0];
assign csrbankarray_csrbank4_txfull_re = ((csrbankarray_csrbank4_sel & csrbankarray_interface4_bank_bus_we) & (csrbankarray_interface4_bank_bus_adr[2:0] == 1'd1));
assign csrbankarray_csrbank4_txfull_we = ((csrbankarray_csrbank4_sel & (~csrbankarray_interface4_bank_bus_we)) & (csrbankarray_interface4_bank_bus_adr[2:0] == 1'd1));
assign csrbankarray_csrbank4_rxempty_r = csrbankarray_interface4_bank_bus_dat_w[0];
assign csrbankarray_csrbank4_rxempty_re = ((csrbankarray_csrbank4_sel & csrbankarray_interface4_bank_bus_we) & (csrbankarray_interface4_bank_bus_adr[2:0] == 2'd2));
assign csrbankarray_csrbank4_rxempty_we = ((csrbankarray_csrbank4_sel & (~csrbankarray_interface4_bank_bus_we)) & (csrbankarray_interface4_bank_bus_adr[2:0] == 2'd2));
assign uart_eventmanager_status_r = csrbankarray_interface4_bank_bus_dat_w[1:0];
assign uart_eventmanager_status_re = ((csrbankarray_csrbank4_sel & csrbankarray_interface4_bank_bus_we) & (csrbankarray_interface4_bank_bus_adr[2:0] == 2'd3));
assign uart_eventmanager_status_we = ((csrbankarray_csrbank4_sel & (~csrbankarray_interface4_bank_bus_we)) & (csrbankarray_interface4_bank_bus_adr[2:0] == 2'd3));
assign uart_eventmanager_pending_r = csrbankarray_interface4_bank_bus_dat_w[1:0];
assign uart_eventmanager_pending_re = ((csrbankarray_csrbank4_sel & csrbankarray_interface4_bank_bus_we) & (csrbankarray_interface4_bank_bus_adr[2:0] == 3'd4));
assign uart_eventmanager_pending_we = ((csrbankarray_csrbank4_sel & (~csrbankarray_interface4_bank_bus_we)) & (csrbankarray_interface4_bank_bus_adr[2:0] == 3'd4));
assign csrbankarray_csrbank4_ev_enable0_r = csrbankarray_interface4_bank_bus_dat_w[1:0];
assign csrbankarray_csrbank4_ev_enable0_re = ((csrbankarray_csrbank4_sel & csrbankarray_interface4_bank_bus_we) & (csrbankarray_interface4_bank_bus_adr[2:0] == 3'd5));
assign csrbankarray_csrbank4_ev_enable0_we = ((csrbankarray_csrbank4_sel & (~csrbankarray_interface4_bank_bus_we)) & (csrbankarray_interface4_bank_bus_adr[2:0] == 3'd5));
assign csrbankarray_csrbank4_txfull_w = uart_txfull_status;
assign uart_txfull_we = csrbankarray_csrbank4_txfull_we;
assign csrbankarray_csrbank4_rxempty_w = uart_rxempty_status;
assign uart_rxempty_we = csrbankarray_csrbank4_rxempty_we;
assign csrbankarray_csrbank4_ev_enable0_w = uart_eventmanager_storage[1:0];
assign csrbankarray_csrbank5_sel = (csrbankarray_interface5_bank_bus_adr[13:9] == 3'd4);
assign csrbankarray_csrbank5_tuning_word3_r = csrbankarray_interface5_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank5_tuning_word3_re = ((csrbankarray_csrbank5_sel & csrbankarray_interface5_bank_bus_we) & (csrbankarray_interface5_bank_bus_adr[1:0] == 1'd0));
assign csrbankarray_csrbank5_tuning_word3_we = ((csrbankarray_csrbank5_sel & (~csrbankarray_interface5_bank_bus_we)) & (csrbankarray_interface5_bank_bus_adr[1:0] == 1'd0));
assign csrbankarray_csrbank5_tuning_word2_r = csrbankarray_interface5_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank5_tuning_word2_re = ((csrbankarray_csrbank5_sel & csrbankarray_interface5_bank_bus_we) & (csrbankarray_interface5_bank_bus_adr[1:0] == 1'd1));
assign csrbankarray_csrbank5_tuning_word2_we = ((csrbankarray_csrbank5_sel & (~csrbankarray_interface5_bank_bus_we)) & (csrbankarray_interface5_bank_bus_adr[1:0] == 1'd1));
assign csrbankarray_csrbank5_tuning_word1_r = csrbankarray_interface5_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank5_tuning_word1_re = ((csrbankarray_csrbank5_sel & csrbankarray_interface5_bank_bus_we) & (csrbankarray_interface5_bank_bus_adr[1:0] == 2'd2));
assign csrbankarray_csrbank5_tuning_word1_we = ((csrbankarray_csrbank5_sel & (~csrbankarray_interface5_bank_bus_we)) & (csrbankarray_interface5_bank_bus_adr[1:0] == 2'd2));
assign csrbankarray_csrbank5_tuning_word0_r = csrbankarray_interface5_bank_bus_dat_w[7:0];
assign csrbankarray_csrbank5_tuning_word0_re = ((csrbankarray_csrbank5_sel & csrbankarray_interface5_bank_bus_we) & (csrbankarray_interface5_bank_bus_adr[1:0] == 2'd3));
assign csrbankarray_csrbank5_tuning_word0_we = ((csrbankarray_csrbank5_sel & (~csrbankarray_interface5_bank_bus_we)) & (csrbankarray_interface5_bank_bus_adr[1:0] == 2'd3));
assign csrbankarray_csrbank5_tuning_word3_w = uart_phy_storage[31:24];
assign csrbankarray_csrbank5_tuning_word2_w = uart_phy_storage[23:16];
assign csrbankarray_csrbank5_tuning_word1_w = uart_phy_storage[15:8];
assign csrbankarray_csrbank5_tuning_word0_w = uart_phy_storage[7:0];
assign csrcon_adr = adr;
assign csrcon_we = we;
assign csrcon_dat_w = dat_w;
assign dat_r = csrcon_dat_r;
assign csrbankarray_interface0_bank_bus_adr = csrcon_adr;
assign csrbankarray_interface1_bank_bus_adr = csrcon_adr;
assign csrbankarray_interface2_bank_bus_adr = csrcon_adr;
assign csrbankarray_interface3_bank_bus_adr = csrcon_adr;
assign csrbankarray_interface4_bank_bus_adr = csrcon_adr;
assign csrbankarray_interface5_bank_bus_adr = csrcon_adr;
assign csrbankarray_sram_bus_adr = csrcon_adr;
assign csrbankarray_interface0_bank_bus_we = csrcon_we;
assign csrbankarray_interface1_bank_bus_we = csrcon_we;
assign csrbankarray_interface2_bank_bus_we = csrcon_we;
assign csrbankarray_interface3_bank_bus_we = csrcon_we;
assign csrbankarray_interface4_bank_bus_we = csrcon_we;
assign csrbankarray_interface5_bank_bus_we = csrcon_we;
assign csrbankarray_sram_bus_we = csrcon_we;
assign csrbankarray_interface0_bank_bus_dat_w = csrcon_dat_w;
assign csrbankarray_interface1_bank_bus_dat_w = csrcon_dat_w;
assign csrbankarray_interface2_bank_bus_dat_w = csrcon_dat_w;
assign csrbankarray_interface3_bank_bus_dat_w = csrcon_dat_w;
assign csrbankarray_interface4_bank_bus_dat_w = csrcon_dat_w;
assign csrbankarray_interface5_bank_bus_dat_w = csrcon_dat_w;
assign csrbankarray_sram_bus_dat_w = csrcon_dat_w;
assign csrcon_dat_r = ((((((csrbankarray_interface0_bank_bus_dat_r | csrbankarray_interface1_bank_bus_dat_r) | csrbankarray_interface2_bank_bus_dat_r) | csrbankarray_interface3_bank_bus_dat_r) | csrbankarray_interface4_bank_bus_dat_r) | csrbankarray_interface5_bank_bus_dat_r) | csrbankarray_sram_bus_dat_r);
always @(*) begin
	array_muxed0 <= 30'd0;
	case (grant)
		1'd0: begin
			array_muxed0 <= interface0_soc_bus_adr;
		end
		default: begin
			array_muxed0 <= interface1_soc_bus_adr;
		end
	endcase
end
always @(*) begin
	array_muxed1 <= 32'd0;
	case (grant)
		1'd0: begin
			array_muxed1 <= interface0_soc_bus_dat_w;
		end
		default: begin
			array_muxed1 <= interface1_soc_bus_dat_w;
		end
	endcase
end
always @(*) begin
	array_muxed2 <= 4'd0;
	case (grant)
		1'd0: begin
			array_muxed2 <= interface0_soc_bus_sel;
		end
		default: begin
			array_muxed2 <= interface1_soc_bus_sel;
		end
	endcase
end
always @(*) begin
	array_muxed3 <= 1'd0;
	case (grant)
		1'd0: begin
			array_muxed3 <= interface0_soc_bus_cyc;
		end
		default: begin
			array_muxed3 <= interface1_soc_bus_cyc;
		end
	endcase
end
always @(*) begin
	array_muxed4 <= 1'd0;
	case (grant)
		1'd0: begin
			array_muxed4 <= interface0_soc_bus_stb;
		end
		default: begin
			array_muxed4 <= interface1_soc_bus_stb;
		end
	endcase
end
always @(*) begin
	array_muxed5 <= 1'd0;
	case (grant)
		1'd0: begin
			array_muxed5 <= interface0_soc_bus_we;
		end
		default: begin
			array_muxed5 <= interface1_soc_bus_we;
		end
	endcase
end
always @(*) begin
	array_muxed6 <= 3'd0;
	case (grant)
		1'd0: begin
			array_muxed6 <= interface0_soc_bus_cti;
		end
		default: begin
			array_muxed6 <= interface1_soc_bus_cti;
		end
	endcase
end
always @(*) begin
	array_muxed7 <= 2'd0;
	case (grant)
		1'd0: begin
			array_muxed7 <= interface0_soc_bus_bte;
		end
		default: begin
			array_muxed7 <= interface1_soc_bus_bte;
		end
	endcase
end
assign uart_phy_rx = regs1;

always @(posedge por_clk) begin
	if ((reset_delay != 1'd0)) begin
		reset_delay <= (reset_delay - 1'd1);
	end
	if (por_rst) begin
		reset_delay <= 12'd4095;
	end
end

always @(posedge sys_clk) begin
	if ((ctrl_bus_errors != 32'd4294967295)) begin
		if (ctrl_bus_error) begin
			ctrl_bus_errors <= (ctrl_bus_errors + 1'd1);
		end
	end
	uart_phy_sink_ready <= 1'd0;
	if (((uart_phy_sink_valid & (~uart_phy_tx_busy)) & (~uart_phy_sink_ready))) begin
		uart_phy_tx_reg <= uart_phy_sink_payload_data;
		uart_phy_tx_bitcount <= 1'd0;
		uart_phy_tx_busy <= 1'd1;
		serial_tx <= 1'd0;
	end else begin
		if ((uart_phy_uart_clk_txen & uart_phy_tx_busy)) begin
			uart_phy_tx_bitcount <= (uart_phy_tx_bitcount + 1'd1);
			if ((uart_phy_tx_bitcount == 4'd8)) begin
				serial_tx <= 1'd1;
			end else begin
				if ((uart_phy_tx_bitcount == 4'd9)) begin
					serial_tx <= 1'd1;
					uart_phy_tx_busy <= 1'd0;
					uart_phy_sink_ready <= 1'd1;
				end else begin
					serial_tx <= uart_phy_tx_reg[0];
					uart_phy_tx_reg <= {1'd0, uart_phy_tx_reg[7:1]};
				end
			end
		end
	end
	if (uart_phy_tx_busy) begin
		{uart_phy_uart_clk_txen, uart_phy_phase_accumulator_tx} <= (uart_phy_phase_accumulator_tx + uart_phy_storage);
	end else begin
		{uart_phy_uart_clk_txen, uart_phy_phase_accumulator_tx} <= 1'd0;
	end
	uart_phy_source_valid <= 1'd0;
	uart_phy_rx_r <= uart_phy_rx;
	if ((~uart_phy_rx_busy)) begin
		if (((~uart_phy_rx) & uart_phy_rx_r)) begin
			uart_phy_rx_busy <= 1'd1;
			uart_phy_rx_bitcount <= 1'd0;
		end
	end else begin
		if (uart_phy_uart_clk_rxen) begin
			uart_phy_rx_bitcount <= (uart_phy_rx_bitcount + 1'd1);
			if ((uart_phy_rx_bitcount == 1'd0)) begin
				if (uart_phy_rx) begin
					uart_phy_rx_busy <= 1'd0;
				end
			end else begin
				if ((uart_phy_rx_bitcount == 4'd9)) begin
					uart_phy_rx_busy <= 1'd0;
					if (uart_phy_rx) begin
						uart_phy_source_payload_data <= uart_phy_rx_reg;
						uart_phy_source_valid <= 1'd1;
					end
				end else begin
					uart_phy_rx_reg <= {uart_phy_rx, uart_phy_rx_reg[7:1]};
				end
			end
		end
	end
	if (uart_phy_rx_busy) begin
		{uart_phy_uart_clk_rxen, uart_phy_phase_accumulator_rx} <= (uart_phy_phase_accumulator_rx + uart_phy_storage);
	end else begin
		{uart_phy_uart_clk_rxen, uart_phy_phase_accumulator_rx} <= 32'd2147483648;
	end
	if (uart_tx_clear) begin
		uart_tx_pending <= 1'd0;
	end
	uart_tx_old_trigger <= uart_tx_trigger;
	if (((~uart_tx_trigger) & uart_tx_old_trigger)) begin
		uart_tx_pending <= 1'd1;
	end
	if (uart_rx_clear) begin
		uart_rx_pending <= 1'd0;
	end
	uart_rx_old_trigger <= uart_rx_trigger;
	if (((~uart_rx_trigger) & uart_rx_old_trigger)) begin
		uart_rx_pending <= 1'd1;
	end
	if (uart_tx_fifo_syncfifo_re) begin
		uart_tx_fifo_readable <= 1'd1;
	end else begin
		if (uart_tx_fifo_re) begin
			uart_tx_fifo_readable <= 1'd0;
		end
	end
	if (((uart_tx_fifo_syncfifo_we & uart_tx_fifo_syncfifo_writable) & (~uart_tx_fifo_replace))) begin
		uart_tx_fifo_produce <= (uart_tx_fifo_produce + 1'd1);
	end
	if (uart_tx_fifo_do_read) begin
		uart_tx_fifo_consume <= (uart_tx_fifo_consume + 1'd1);
	end
	if (((uart_tx_fifo_syncfifo_we & uart_tx_fifo_syncfifo_writable) & (~uart_tx_fifo_replace))) begin
		if ((~uart_tx_fifo_do_read)) begin
			uart_tx_fifo_level0 <= (uart_tx_fifo_level0 + 1'd1);
		end
	end else begin
		if (uart_tx_fifo_do_read) begin
			uart_tx_fifo_level0 <= (uart_tx_fifo_level0 - 1'd1);
		end
	end
	if (uart_rx_fifo_syncfifo_re) begin
		uart_rx_fifo_readable <= 1'd1;
	end else begin
		if (uart_rx_fifo_re) begin
			uart_rx_fifo_readable <= 1'd0;
		end
	end
	if (((uart_rx_fifo_syncfifo_we & uart_rx_fifo_syncfifo_writable) & (~uart_rx_fifo_replace))) begin
		uart_rx_fifo_produce <= (uart_rx_fifo_produce + 1'd1);
	end
	if (uart_rx_fifo_do_read) begin
		uart_rx_fifo_consume <= (uart_rx_fifo_consume + 1'd1);
	end
	if (((uart_rx_fifo_syncfifo_we & uart_rx_fifo_syncfifo_writable) & (~uart_rx_fifo_replace))) begin
		if ((~uart_rx_fifo_do_read)) begin
			uart_rx_fifo_level0 <= (uart_rx_fifo_level0 + 1'd1);
		end
	end else begin
		if (uart_rx_fifo_do_read) begin
			uart_rx_fifo_level0 <= (uart_rx_fifo_level0 - 1'd1);
		end
	end
	if (uart_reset) begin
		uart_tx_pending <= 1'd0;
		uart_tx_old_trigger <= 1'd0;
		uart_rx_pending <= 1'd0;
		uart_rx_old_trigger <= 1'd0;
		uart_tx_fifo_readable <= 1'd0;
		uart_tx_fifo_level0 <= 5'd0;
		uart_tx_fifo_produce <= 4'd0;
		uart_tx_fifo_consume <= 4'd0;
		uart_rx_fifo_readable <= 1'd0;
		uart_rx_fifo_level0 <= 5'd0;
		uart_rx_fifo_produce <= 4'd0;
		uart_rx_fifo_consume <= 4'd0;
	end
	if (timer0_en_storage) begin
		if ((timer0_value == 1'd0)) begin
			timer0_value <= timer0_reload_storage;
		end else begin
			timer0_value <= (timer0_value - 1'd1);
		end
	end else begin
		timer0_value <= timer0_load_storage;
	end
	if (timer0_update_value_re) begin
		timer0_value_status <= timer0_value;
	end
	if (timer0_zero_clear) begin
		timer0_zero_pending <= 1'd0;
	end
	timer0_zero_old_trigger <= timer0_zero_trigger;
	if (((~timer0_zero_trigger) & timer0_zero_old_trigger)) begin
		timer0_zero_pending <= 1'd1;
	end
	state <= next_state;
	if ((spiflash_i == 1'd0)) begin
		spiflash_clk1 <= 1'd1;
		spiflash_miso1 <= spiflash_miso;
	end
	if ((spiflash_i == 1'd1)) begin
		spiflash_i <= 1'd0;
		spiflash_clk1 <= 1'd0;
		spiflash_sr <= {spiflash_sr[30:0], spiflash_miso1};
	end else begin
		spiflash_i <= (spiflash_i + 1'd1);
	end
	if ((((spiflash_bus_cyc & spiflash_bus_stb) & (spiflash_i == 1'd1)) & (spiflash_counter == 1'd0))) begin
		spiflash_cs_n1 <= 1'd0;
		spiflash_sr[31:24] <= 4'd11;
	end
	if ((spiflash_counter == 5'd16)) begin
		spiflash_sr[31:8] <= {spiflash_bus_adr, {2{1'd0}}};
	end
	if ((spiflash_counter == 7'd64)) begin
	end
	if ((spiflash_counter == 8'd144)) begin
		spiflash_bus_ack <= 1'd1;
		spiflash_cs_n1 <= 1'd1;
	end
	if ((spiflash_counter == 8'd145)) begin
		spiflash_bus_ack <= 1'd0;
	end
	if ((spiflash_counter == 8'd147)) begin
	end
	if ((spiflash_counter == 8'd147)) begin
		spiflash_counter <= 1'd0;
	end else begin
		if ((spiflash_counter != 1'd0)) begin
			spiflash_counter <= (spiflash_counter + 1'd1);
		end else begin
			if (((spiflash_bus_cyc & spiflash_bus_stb) & (spiflash_i == 1'd1))) begin
				spiflash_counter <= 1'd1;
			end
		end
	end
	spram_bus_ack <= 1'd0;
	if (((spram_bus_stb & spram_bus_cyc) & (~spram_bus_ack))) begin
		spram_bus_ack <= 1'd1;
	end
	case (grant)
		1'd0: begin
			if ((~request[0])) begin
				if (request[1]) begin
					grant <= 1'd1;
				end
			end
		end
		1'd1: begin
			if ((~request[1])) begin
				if (request[0]) begin
					grant <= 1'd0;
				end
			end
		end
	endcase
	slave_sel_r <= slave_sel;
	if (wait_1) begin
		if ((~done)) begin
			count <= (count - 1'd1);
		end
	end else begin
		count <= 20'd1000000;
	end
	csrbankarray_interface0_bank_bus_dat_r <= 1'd0;
	if (csrbankarray_csrbank0_sel) begin
		case (csrbankarray_interface0_bank_bus_adr[0])
			1'd0: begin
				csrbankarray_interface0_bank_bus_dat_r <= csrbankarray_csrbank0_leds_out0_w;
			end
		endcase
	end
	if (csrbankarray_csrbank0_leds_out0_re) begin
		leds_storage[2:0] <= csrbankarray_csrbank0_leds_out0_r;
	end
	leds_re <= csrbankarray_csrbank0_leds_out0_re;
	csrbankarray_interface1_bank_bus_dat_r <= 1'd0;
	if (csrbankarray_csrbank1_sel) begin
		case (csrbankarray_interface1_bank_bus_adr[3:0])
			1'd0: begin
				csrbankarray_interface1_bank_bus_dat_r <= ctrl_reset_reset_w;
			end
			1'd1: begin
				csrbankarray_interface1_bank_bus_dat_r <= csrbankarray_csrbank1_scratch3_w;
			end
			2'd2: begin
				csrbankarray_interface1_bank_bus_dat_r <= csrbankarray_csrbank1_scratch2_w;
			end
			2'd3: begin
				csrbankarray_interface1_bank_bus_dat_r <= csrbankarray_csrbank1_scratch1_w;
			end
			3'd4: begin
				csrbankarray_interface1_bank_bus_dat_r <= csrbankarray_csrbank1_scratch0_w;
			end
			3'd5: begin
				csrbankarray_interface1_bank_bus_dat_r <= csrbankarray_csrbank1_bus_errors3_w;
			end
			3'd6: begin
				csrbankarray_interface1_bank_bus_dat_r <= csrbankarray_csrbank1_bus_errors2_w;
			end
			3'd7: begin
				csrbankarray_interface1_bank_bus_dat_r <= csrbankarray_csrbank1_bus_errors1_w;
			end
			4'd8: begin
				csrbankarray_interface1_bank_bus_dat_r <= csrbankarray_csrbank1_bus_errors0_w;
			end
		endcase
	end
	if (csrbankarray_csrbank1_scratch3_re) begin
		ctrl_storage[31:24] <= csrbankarray_csrbank1_scratch3_r;
	end
	if (csrbankarray_csrbank1_scratch2_re) begin
		ctrl_storage[23:16] <= csrbankarray_csrbank1_scratch2_r;
	end
	if (csrbankarray_csrbank1_scratch1_re) begin
		ctrl_storage[15:8] <= csrbankarray_csrbank1_scratch1_r;
	end
	if (csrbankarray_csrbank1_scratch0_re) begin
		ctrl_storage[7:0] <= csrbankarray_csrbank1_scratch0_r;
	end
	ctrl_re <= csrbankarray_csrbank1_scratch0_re;
	csrbankarray_sel_r <= csrbankarray_sel;
	csrbankarray_interface2_bank_bus_dat_r <= 1'd0;
	if (csrbankarray_csrbank2_sel) begin
		case (csrbankarray_interface2_bank_bus_adr[1:0])
			1'd0: begin
				csrbankarray_interface2_bank_bus_dat_r <= csrbankarray_csrbank2_bitbang0_w;
			end
			1'd1: begin
				csrbankarray_interface2_bank_bus_dat_r <= csrbankarray_csrbank2_miso_w;
			end
			2'd2: begin
				csrbankarray_interface2_bank_bus_dat_r <= csrbankarray_csrbank2_bitbang_en0_w;
			end
		endcase
	end
	if (csrbankarray_csrbank2_bitbang0_re) begin
		spiflash_bitbang_storage[3:0] <= csrbankarray_csrbank2_bitbang0_r;
	end
	spiflash_bitbang_re <= csrbankarray_csrbank2_bitbang0_re;
	if (csrbankarray_csrbank2_bitbang_en0_re) begin
		spiflash_bitbang_en_storage <= csrbankarray_csrbank2_bitbang_en0_r;
	end
	spiflash_bitbang_en_re <= csrbankarray_csrbank2_bitbang_en0_re;
	csrbankarray_interface3_bank_bus_dat_r <= 1'd0;
	if (csrbankarray_csrbank3_sel) begin
		case (csrbankarray_interface3_bank_bus_adr[4:0])
			1'd0: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_load3_w;
			end
			1'd1: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_load2_w;
			end
			2'd2: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_load1_w;
			end
			2'd3: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_load0_w;
			end
			3'd4: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_reload3_w;
			end
			3'd5: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_reload2_w;
			end
			3'd6: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_reload1_w;
			end
			3'd7: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_reload0_w;
			end
			4'd8: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_en0_w;
			end
			4'd9: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_update_value0_w;
			end
			4'd10: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_value3_w;
			end
			4'd11: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_value2_w;
			end
			4'd12: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_value1_w;
			end
			4'd13: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_value0_w;
			end
			4'd14: begin
				csrbankarray_interface3_bank_bus_dat_r <= timer0_eventmanager_status_w;
			end
			4'd15: begin
				csrbankarray_interface3_bank_bus_dat_r <= timer0_eventmanager_pending_w;
			end
			5'd16: begin
				csrbankarray_interface3_bank_bus_dat_r <= csrbankarray_csrbank3_ev_enable0_w;
			end
		endcase
	end
	if (csrbankarray_csrbank3_load3_re) begin
		timer0_load_storage[31:24] <= csrbankarray_csrbank3_load3_r;
	end
	if (csrbankarray_csrbank3_load2_re) begin
		timer0_load_storage[23:16] <= csrbankarray_csrbank3_load2_r;
	end
	if (csrbankarray_csrbank3_load1_re) begin
		timer0_load_storage[15:8] <= csrbankarray_csrbank3_load1_r;
	end
	if (csrbankarray_csrbank3_load0_re) begin
		timer0_load_storage[7:0] <= csrbankarray_csrbank3_load0_r;
	end
	timer0_load_re <= csrbankarray_csrbank3_load0_re;
	if (csrbankarray_csrbank3_reload3_re) begin
		timer0_reload_storage[31:24] <= csrbankarray_csrbank3_reload3_r;
	end
	if (csrbankarray_csrbank3_reload2_re) begin
		timer0_reload_storage[23:16] <= csrbankarray_csrbank3_reload2_r;
	end
	if (csrbankarray_csrbank3_reload1_re) begin
		timer0_reload_storage[15:8] <= csrbankarray_csrbank3_reload1_r;
	end
	if (csrbankarray_csrbank3_reload0_re) begin
		timer0_reload_storage[7:0] <= csrbankarray_csrbank3_reload0_r;
	end
	timer0_reload_re <= csrbankarray_csrbank3_reload0_re;
	if (csrbankarray_csrbank3_en0_re) begin
		timer0_en_storage <= csrbankarray_csrbank3_en0_r;
	end
	timer0_en_re <= csrbankarray_csrbank3_en0_re;
	if (csrbankarray_csrbank3_update_value0_re) begin
		timer0_update_value_storage <= csrbankarray_csrbank3_update_value0_r;
	end
	timer0_update_value_re <= csrbankarray_csrbank3_update_value0_re;
	if (csrbankarray_csrbank3_ev_enable0_re) begin
		timer0_eventmanager_storage <= csrbankarray_csrbank3_ev_enable0_r;
	end
	timer0_eventmanager_re <= csrbankarray_csrbank3_ev_enable0_re;
	csrbankarray_interface4_bank_bus_dat_r <= 1'd0;
	if (csrbankarray_csrbank4_sel) begin
		case (csrbankarray_interface4_bank_bus_adr[2:0])
			1'd0: begin
				csrbankarray_interface4_bank_bus_dat_r <= uart_rxtx_w;
			end
			1'd1: begin
				csrbankarray_interface4_bank_bus_dat_r <= csrbankarray_csrbank4_txfull_w;
			end
			2'd2: begin
				csrbankarray_interface4_bank_bus_dat_r <= csrbankarray_csrbank4_rxempty_w;
			end
			2'd3: begin
				csrbankarray_interface4_bank_bus_dat_r <= uart_eventmanager_status_w;
			end
			3'd4: begin
				csrbankarray_interface4_bank_bus_dat_r <= uart_eventmanager_pending_w;
			end
			3'd5: begin
				csrbankarray_interface4_bank_bus_dat_r <= csrbankarray_csrbank4_ev_enable0_w;
			end
		endcase
	end
	if (csrbankarray_csrbank4_ev_enable0_re) begin
		uart_eventmanager_storage[1:0] <= csrbankarray_csrbank4_ev_enable0_r;
	end
	uart_eventmanager_re <= csrbankarray_csrbank4_ev_enable0_re;
	csrbankarray_interface5_bank_bus_dat_r <= 1'd0;
	if (csrbankarray_csrbank5_sel) begin
		case (csrbankarray_interface5_bank_bus_adr[1:0])
			1'd0: begin
				csrbankarray_interface5_bank_bus_dat_r <= csrbankarray_csrbank5_tuning_word3_w;
			end
			1'd1: begin
				csrbankarray_interface5_bank_bus_dat_r <= csrbankarray_csrbank5_tuning_word2_w;
			end
			2'd2: begin
				csrbankarray_interface5_bank_bus_dat_r <= csrbankarray_csrbank5_tuning_word1_w;
			end
			2'd3: begin
				csrbankarray_interface5_bank_bus_dat_r <= csrbankarray_csrbank5_tuning_word0_w;
			end
		endcase
	end
	if (csrbankarray_csrbank5_tuning_word3_re) begin
		uart_phy_storage[31:24] <= csrbankarray_csrbank5_tuning_word3_r;
	end
	if (csrbankarray_csrbank5_tuning_word2_re) begin
		uart_phy_storage[23:16] <= csrbankarray_csrbank5_tuning_word2_r;
	end
	if (csrbankarray_csrbank5_tuning_word1_re) begin
		uart_phy_storage[15:8] <= csrbankarray_csrbank5_tuning_word1_r;
	end
	if (csrbankarray_csrbank5_tuning_word0_re) begin
		uart_phy_storage[7:0] <= csrbankarray_csrbank5_tuning_word0_r;
	end
	uart_phy_re <= csrbankarray_csrbank5_tuning_word0_re;
	if (sys_rst) begin
		ctrl_storage <= 32'd305419896;
		ctrl_re <= 1'd0;
		ctrl_bus_errors <= 32'd0;
		serial_tx <= 1'd1;
		uart_phy_storage <= 32'd41231686;
		uart_phy_re <= 1'd0;
		uart_phy_sink_ready <= 1'd0;
		uart_phy_uart_clk_txen <= 1'd0;
		uart_phy_phase_accumulator_tx <= 32'd0;
		uart_phy_tx_reg <= 8'd0;
		uart_phy_tx_bitcount <= 4'd0;
		uart_phy_tx_busy <= 1'd0;
		uart_phy_source_valid <= 1'd0;
		uart_phy_source_payload_data <= 8'd0;
		uart_phy_uart_clk_rxen <= 1'd0;
		uart_phy_phase_accumulator_rx <= 32'd0;
		uart_phy_rx_r <= 1'd0;
		uart_phy_rx_reg <= 8'd0;
		uart_phy_rx_bitcount <= 4'd0;
		uart_phy_rx_busy <= 1'd0;
		uart_tx_pending <= 1'd0;
		uart_tx_old_trigger <= 1'd0;
		uart_rx_pending <= 1'd0;
		uart_rx_old_trigger <= 1'd0;
		uart_eventmanager_storage <= 2'd0;
		uart_eventmanager_re <= 1'd0;
		uart_tx_fifo_readable <= 1'd0;
		uart_tx_fifo_level0 <= 5'd0;
		uart_tx_fifo_produce <= 4'd0;
		uart_tx_fifo_consume <= 4'd0;
		uart_rx_fifo_readable <= 1'd0;
		uart_rx_fifo_level0 <= 5'd0;
		uart_rx_fifo_produce <= 4'd0;
		uart_rx_fifo_consume <= 4'd0;
		timer0_load_storage <= 32'd0;
		timer0_load_re <= 1'd0;
		timer0_reload_storage <= 32'd0;
		timer0_reload_re <= 1'd0;
		timer0_en_storage <= 1'd0;
		timer0_en_re <= 1'd0;
		timer0_update_value_storage <= 1'd0;
		timer0_update_value_re <= 1'd0;
		timer0_value_status <= 32'd0;
		timer0_zero_pending <= 1'd0;
		timer0_zero_old_trigger <= 1'd0;
		timer0_eventmanager_storage <= 1'd0;
		timer0_eventmanager_re <= 1'd0;
		timer0_value <= 32'd0;
		leds_storage <= 3'd0;
		leds_re <= 1'd0;
		spiflash_bus_ack <= 1'd0;
		spiflash_bitbang_storage <= 4'd0;
		spiflash_bitbang_re <= 1'd0;
		spiflash_bitbang_en_storage <= 1'd0;
		spiflash_bitbang_en_re <= 1'd0;
		spiflash_cs_n1 <= 1'd1;
		spiflash_clk1 <= 1'd0;
		spiflash_sr <= 32'd0;
		spiflash_i <= 1'd0;
		spiflash_miso1 <= 1'd0;
		spiflash_counter <= 8'd0;
		spram_bus_ack <= 1'd0;
		state <= 1'd0;
		grant <= 1'd0;
		slave_sel_r <= 3'd0;
		count <= 20'd1000000;
		csrbankarray_interface0_bank_bus_dat_r <= 8'd0;
		csrbankarray_interface1_bank_bus_dat_r <= 8'd0;
		csrbankarray_sel_r <= 1'd0;
		csrbankarray_interface2_bank_bus_dat_r <= 8'd0;
		csrbankarray_interface3_bank_bus_dat_r <= 8'd0;
		csrbankarray_interface4_bank_bus_dat_r <= 8'd0;
		csrbankarray_interface5_bank_bus_dat_r <= 8'd0;
	end
	regs0 <= serial_rx;
	regs1 <= regs0;
end

reg [9:0] storage[0:15];
reg [9:0] memdat;
reg [9:0] memdat_1;
always @(posedge sys_clk) begin
	if (uart_tx_fifo_wrport_we)
		storage[uart_tx_fifo_wrport_adr] <= uart_tx_fifo_wrport_dat_w;
	memdat <= storage[uart_tx_fifo_wrport_adr];
end

always @(posedge sys_clk) begin
	if (uart_tx_fifo_rdport_re)
		memdat_1 <= storage[uart_tx_fifo_rdport_adr];
end

assign uart_tx_fifo_wrport_dat_r = memdat;
assign uart_tx_fifo_rdport_dat_r = memdat_1;

reg [9:0] storage_1[0:15];
reg [9:0] memdat_2;
reg [9:0] memdat_3;
always @(posedge sys_clk) begin
	if (uart_rx_fifo_wrport_we)
		storage_1[uart_rx_fifo_wrport_adr] <= uart_rx_fifo_wrport_dat_w;
	memdat_2 <= storage_1[uart_rx_fifo_wrport_adr];
end

always @(posedge sys_clk) begin
	if (uart_rx_fifo_rdport_re)
		memdat_3 <= storage_1[uart_rx_fifo_rdport_adr];
end

assign uart_rx_fifo_wrport_dat_r = memdat_2;
assign uart_rx_fifo_rdport_dat_r = memdat_3;

reg [7:0] mem[0:7];
reg [2:0] memadr;
always @(posedge sys_clk) begin
	memadr <= csrbankarray_adr;
end

assign csrbankarray_dat_r = mem[memadr];

initial begin
	$readmemh("mem.init", mem);
end

SB_HFOSC #(
	.CLKHF_DIV("0b10")
) SB_HFOSC (
	.CLKHFEN(1'd1),
	.CLKHFPU(1'd1),
	.CLKHF(sb_hfosc)
);

SB_SPRAM256KA SB_SPRAM256KA(
	.ADDRESS(spram_bus_adr[13:0]),
	.CHIPSELECT(1'd1),
	.CLOCK(sys_clk),
	.DATAIN(spram_datain00),
	.MASKWREN(spram_maskwren00),
	.POWEROFF(1'd1),
	.SLEEP(1'd0),
	.STANDBY(1'd0),
	.WREN(spram_wren0),
	.DATAOUT(spram_dataout00)
);

SB_SPRAM256KA SB_SPRAM256KA_1(
	.ADDRESS(spram_bus_adr[13:0]),
	.CHIPSELECT(1'd1),
	.CLOCK(sys_clk),
	.DATAIN(spram_datain10),
	.MASKWREN(spram_maskwren10),
	.POWEROFF(1'd1),
	.SLEEP(1'd0),
	.STANDBY(1'd0),
	.WREN(spram_wren0),
	.DATAOUT(spram_dataout10)
);

SB_SPRAM256KA SB_SPRAM256KA_2(
	.ADDRESS(spram_bus_adr[13:0]),
	.CHIPSELECT(1'd1),
	.CLOCK(sys_clk),
	.DATAIN(spram_datain01),
	.MASKWREN(spram_maskwren01),
	.POWEROFF(1'd1),
	.SLEEP(1'd0),
	.STANDBY(1'd0),
	.WREN(spram_wren1),
	.DATAOUT(spram_dataout01)
);

SB_SPRAM256KA SB_SPRAM256KA_3(
	.ADDRESS(spram_bus_adr[13:0]),
	.CHIPSELECT(1'd1),
	.CLOCK(sys_clk),
	.DATAIN(spram_datain11),
	.MASKWREN(spram_maskwren11),
	.POWEROFF(1'd1),
	.SLEEP(1'd0),
	.STANDBY(1'd0),
	.WREN(spram_wren1),
	.DATAOUT(spram_dataout11)
);

lm32_cpu #(
	.eba_reset(32'h20020000)
) lm32_cpu (
	.D_ACK_I(cpu_dbus_ack),
	.D_DAT_I(cpu_dbus_dat_r),
	.D_ERR_I(cpu_dbus_err),
	.D_RTY_I(1'd0),
	.I_ACK_I(cpu_ibus_ack),
	.I_DAT_I(cpu_ibus_dat_r),
	.I_ERR_I(cpu_ibus_err),
	.I_RTY_I(1'd0),
	.clk_i(sys_clk),
	.interrupt(cpu_interrupt),
	.rst_i((sys_rst | cpu_reset)),
	.D_ADR_O(cpu_d_adr_o),
	.D_BTE_O(cpu_dbus_bte),
	.D_CTI_O(cpu_dbus_cti),
	.D_CYC_O(cpu_dbus_cyc),
	.D_DAT_O(cpu_dbus_dat_w),
	.D_SEL_O(cpu_dbus_sel),
	.D_STB_O(cpu_dbus_stb),
	.D_WE_O(cpu_dbus_we),
	.I_ADR_O(cpu_i_adr_o),
	.I_BTE_O(cpu_ibus_bte),
	.I_CTI_O(cpu_ibus_cti),
	.I_CYC_O(cpu_ibus_cyc),
	.I_DAT_O(cpu_ibus_dat_w),
	.I_SEL_O(cpu_ibus_sel),
	.I_STB_O(cpu_ibus_stb),
	.I_WE_O(cpu_ibus_we)
);

SB_DFFS SB_DFFS(
	.C(por_clk),
	.D(1'd0),
	.S(reset),
	.Q(rst1)
);

SB_DFFS SB_DFFS_1(
	.C(por_clk),
	.D(rst1),
	.S(reset),
	.Q(por_rst)
);

endmodule
