# Autogenerated by LiteX / git: 02bfda5e
set -e
source /home/travis/build/timvideos/HDMI2USB-litex-firmware/build/Xilinx/opt/Xilinx/14.7/ISE_DS/settings64.sh

xst -ifn top.xst

netgen -ofmt verilog -w -sim top.ngc top_synth.v

ngdbuild  -uc top.ucf top.ngc top.ngd

map -ol high -w -o top_map.ncd top.ngd top.pcf
par -ol high -w top_map.ncd top.ncd top.pcf
bitgen -g Binary:Yes -w -g ProgPin:PullUp  -g DonePin:PullUp  -g TckPin:PullNone  -g TdiPin:PullNone  -g TdoPin:PullNone  -g TmsPin:PullNone  -g UnusedPin:PullNone  top.ncd top.bit
