# Autogenerated by LiteX / git: 02bfda5e
set -e
yosys -q -l top.rpt top.ys
nextpnr-ice40 --hx8k --package cb132 --pcf top.pcf --json top.json --asc top.txt --pre-pack top_pre_pack.py
icepack -s top.txt top.bin
